// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxkvszcfjybqhtzohcsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a3ZzemNmanlicWh0em9oY3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3Nzg0MjMsImV4cCI6MjA1NzM1NDQyM30.ev0A-3bWyec8nrH_DF9kiinNCAVoFX2aTx3w0z-p1CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);